version: '3.8'

services:
  postgres:
    image: postgres
    container_name: postegresdb_atv_docker
    env_file: 
      - .env
    environment: 
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5432:5432"
