version: '3.8'

services:
  postgres:
    image: postgres
    container_name: postegresdb_atv_docker
    env_file: 
      - .env
    environment: 
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5432:5432"
  
  api:
    build: 
      context: .
      dockerfile: dockerfile.api
    container_name: nest-api_atv_docker
    env_file:
      - .env
    ports:
      - "${PORT}:${PORT}"
    depends_on: 
      - postgres
    environment:
      DATABASE_URL: ${DATABASE_URL_CONTAINER}
    command: sh -c "npx prisma migrate deploy && npm run start:prod"